services:
  discovery-service:
    image: discovery-test
    build: ./discovery-server
    ports:
      - 8761:8761
    mem_limit: 700m
    environment:
      - eureka.instance.prefer-ip-address= true
    depends_on:
     - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - C:\Users\Halef\Desktop\Turkcell_JAVA\volumes\keycloak:/opt/keycloak/data

  api-gateway:
    image: test-key
    build: ./api-gateway
    ports:
      - 8181:8181
    mem_limit: 700m
    environment:
      - eureka.instance.prefer-ip-address=true
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/rent-a-car-microservices
    depends_on:
      - discovery-service

  customer-service:
    image: halefbudanur/customer-service
    ports:
      - 8083:8083
    mem_limit: 700m
    environment:
      - eureka.instance.prefer-ip-address=true
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka

  rental-service:
      image: fuathuriyetoglu/rental-service
      ports:
        - 8081:8081
      mem_limit: 700m
      environment:
        - eureka.instance.prefer-ip-address=true
        - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
        - spring.kafka.bootstrap-servers=kafka:9092
      depends_on:
        - discovery-service
        - api-gateway
        - notificationservice

  notificationservice:
    image: halefbudanur/notificationservice
    ports:
      - 8085:8085
    mem_limit: 700m
    environment:
      - spring.kafka.bootstrap-servers=kafka:9092
    depends_on:
      - kafka

  car-service:
    image: halefbudanur/car-service
    ports:
      - 8082:8082
    mem_limit: 700m
    environment:
      - eureka.instance.prefer-ip-address=true
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
      - api-gateway

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-manager:
    image: hlebalbau/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:



